steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/gcloud-sops', '.']
- name: 'eu.gcr.io/$PROJECT_ID/gcloud-sops'
  args: ['-v']
images: ['eu.gcr.io/$PROJECT_ID/gcloud-sops']